### ISSUE TITLE
NumberFormat error

### ISSUE THREAD

**Issue by davidsowerby** [davidsowerby/q3c-gradle#19]
Caused by: java.lang.NumberFormatException: For input string: "TOC-Releasing-q3c-gradle)"
	at uk.q3c.gradle.PrepareReleaseTaskDelegate.expandIssueReferences(PrepareReleaseTaskDelegate.java:242)
	at uk.q3c.gradle.PrepareReleaseTaskDelegate.createReleaseNotes(PrepareReleaseTaskDelegate.java:110)
	at uk.q3c.gradle.PrepareReleaseTaskDelegate.execute(PrepareReleaseTaskDelegate.java:61)
	at uk.q3c.gradle.PrepareReleaseTask.release(PrepareReleaseTask.java:37)
	... 52 more

**Comment by davidsowerby** [comment]
This will probably occur with any commit comment which contains a '#' which is not actually an issue reference
